// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// createModel_DynamicActions
List createModel_DynamicActions(int n_units, int n_species, int n_threats, Rcpp::DataFrame Jk, Rcpp::DataFrame Ij, Rcpp::DataFrame Ik, Rcpp::DataFrame ExpansionType, Rcpp::DataFrame Dlong, Rcpp::DataFrame Adyacency, Rcpp::DataFrame Dradial, Rcpp::DataFrame Ck, int levels, int periods, double budget_per_period, int objective);
RcppExport SEXP _dynamicsthR_createModel_DynamicActions(SEXP n_unitsSEXP, SEXP n_speciesSEXP, SEXP n_threatsSEXP, SEXP JkSEXP, SEXP IjSEXP, SEXP IkSEXP, SEXP ExpansionTypeSEXP, SEXP DlongSEXP, SEXP AdyacencySEXP, SEXP DradialSEXP, SEXP CkSEXP, SEXP levelsSEXP, SEXP periodsSEXP, SEXP budget_per_periodSEXP, SEXP objectiveSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< int >::type n_units(n_unitsSEXP);
    Rcpp::traits::input_parameter< int >::type n_species(n_speciesSEXP);
    Rcpp::traits::input_parameter< int >::type n_threats(n_threatsSEXP);
    Rcpp::traits::input_parameter< Rcpp::DataFrame >::type Jk(JkSEXP);
    Rcpp::traits::input_parameter< Rcpp::DataFrame >::type Ij(IjSEXP);
    Rcpp::traits::input_parameter< Rcpp::DataFrame >::type Ik(IkSEXP);
    Rcpp::traits::input_parameter< Rcpp::DataFrame >::type ExpansionType(ExpansionTypeSEXP);
    Rcpp::traits::input_parameter< Rcpp::DataFrame >::type Dlong(DlongSEXP);
    Rcpp::traits::input_parameter< Rcpp::DataFrame >::type Adyacency(AdyacencySEXP);
    Rcpp::traits::input_parameter< Rcpp::DataFrame >::type Dradial(DradialSEXP);
    Rcpp::traits::input_parameter< Rcpp::DataFrame >::type Ck(CkSEXP);
    Rcpp::traits::input_parameter< int >::type levels(levelsSEXP);
    Rcpp::traits::input_parameter< int >::type periods(periodsSEXP);
    Rcpp::traits::input_parameter< double >::type budget_per_period(budget_per_periodSEXP);
    Rcpp::traits::input_parameter< int >::type objective(objectiveSEXP);
    rcpp_result_gen = Rcpp::wrap(createModel_DynamicActions(n_units, n_species, n_threats, Jk, Ij, Ik, ExpansionType, Dlong, Adyacency, Dradial, Ck, levels, periods, budget_per_period, objective));
    return rcpp_result_gen;
END_RCPP
}

RcppExport SEXP _rcpp_module_boot_yada();

static const R_CallMethodDef CallEntries[] = {
    {"_dynamicsthR_createModel_DynamicActions", (DL_FUNC) &_dynamicsthR_createModel_DynamicActions, 15},
    {"_rcpp_module_boot_yada", (DL_FUNC) &_rcpp_module_boot_yada, 0},
    {NULL, NULL, 0}
};

RcppExport void R_init_dynamicsthR(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
