# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

createModel_DynamicActions <- function(n_units, n_species, n_threats, Jk, Ij, Ik, ExpansionType, Dlong, Adyacency, Dradial, Ck, levels, periods, budget_per_period) {
    .Call(`_dynamicsthR_createModel_DynamicActions`, n_units, n_species, n_threats, Jk, Ij, Ik, ExpansionType, Dlong, Adyacency, Dradial, Ck, levels, periods, budget_per_period)
}

rcpp_hello_world <- function() {
    .Call(`_dynamicsthR_rcpp_hello_world`)
}

